name: run OrangeHRM Cypress tests
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: run Orange HRM Cypress tests with Chrome
        uses: cypress-io/github-action@v3
        timeout-minutes: 10
        with:
          browser: chrome
